### ISSUE TITLE
We're doooooooooooooooooooown!!!

### ISSUE THREAD

**Issue by bascht** [findoutwho/hasbeen.at#20]
http://downforeveryoneorjustme.com/hasbeen.at

Will it come back?

**Comment by schultyy** [comment]
Damnit. I see what I can do this evening

**Comment by schultyy** [comment]
and we're back 

![http://i.giphy.com/soitAQThr9FOU.gif](http://i.giphy.com/soitAQThr9FOU.gif)

**Comment by schultyy** [comment]
I guess I need to spend some time to rebuild the VM. It's over 2 years old and it's out of the support cycle.
